# Generated by Django 4.0.3 on 2022-03-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='name',
        ),
        migrations.AddField(
            model_name='blogger',
            name='first_name',
            field=models.CharField(help_text='Blogger first name', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='blogger',
            name='last_name',
            field=models.CharField(help_text='Blogger last name', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='comments',
            field=models.ManyToManyField(blank=True, editable=False, help_text='comments for this post', to='web.comment'),
        ),
    ]
