# Generated by Django 4.0.3 on 2022-03-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_blogger_name_blogger_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=models.CharField(help_text='Blog title', max_length=100), help_text='for URL purposes.', max_length=100),
        ),
    ]
